///////////////////////////////////////////////////////////
//  Booking.cs
//  Implementation of the Class Booking
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:36 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public class Booking {

		private int amount;
		private string date;
		private string facilityName;
		private string paymentType;
		private string purpose;

		public Booking(){

		}

		~Booking(){

		}

		public void BookFacility(){

		}

		public void display(){

		}

		public void payment(){

		}

		public void update(){

		}

	}//end Booking

}//end namespace Application