///////////////////////////////////////////////////////////
//  Parking.cs
//  Implementation of the Class Parking
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:40 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public class Parking {

		private double balance;
		private string plateNo;
		private string time;
		private string zone;

		public Parking(){

		}

		~Parking(){

		}

		public void AddParking(){

		}

		public void DisplayMessage(){

		}

		public void payParking(){

		}

		public void selectVehicle(){

		}

	}//end Parking

}//end namespace Application