///////////////////////////////////////////////////////////
//  Register.cs
//  Implementation of the Class Register
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:41 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public class Register {

		private string email;
		private string password;

		public Register(){

		}

		~Register(){

		}

		public void DisplayMessage(){

		}

		public void login(){

		}

		public register(){

		}

	}//end Register

}//end namespace Application