///////////////////////////////////////////////////////////
//  Reload.cs
//  Implementation of the Class Reload
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:43 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public class Reload {

		private int amount;
		private string bankName;
		private int phoneNo;

		public Reload(){

		}

		~Reload(){

		}

		public void payment(){

		}

		public reload(){

		}

		public void updateBalance(){

		}

	}//end Reload

}//end namespace Application