///////////////////////////////////////////////////////////
//  Vehicle.cs
//  Implementation of the Class Vehicle
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:44 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace Application {
	public class Vehicle {

		private string color;
		private string model;
		private string plateNo;

		public Vehicle(){

		}

		~Vehicle(){

		}

		public void checkVehicle(){

		}

		public void DisplayMessage(){

		}

		public void registerVehicle(){

		}

	}//end Vehicle

}//end namespace Application