///////////////////////////////////////////////////////////
//  Booking.cs
//  Implementation of the Class Booking
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:36 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DAL;



namespace BLL {
	public class Booking {

		private int amount;
		private string date;
		private string facilityName;
		private string paymentType;
		private string purpose;

        BookingDataLayer objDAL = new BookingDataLayer();
		public Booking(){

		}

		~Booking(){

		}

		public void BookFacility(int amount , string date, string facilityName, string paymentType, string purpose){
            objDAL.InsertData(amount, date, facilityName, paymentType, purpose);

		}

		public void display(){

		}

		public void payment(){

		}

		public void update(){

		}

	}//end Booking

}//end namespace Application