///////////////////////////////////////////////////////////
//  Parking.cs
//  Implementation of the Class Parking
//  Generated by Enterprise Architect
//  Created on:      15-May-2019 3:56:40 PM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Data.SqlClient;
using DAL;



namespace BLL {
	public class Parking {

        private double balance { get; set; }
        private string plateNo;
        private string date;
		private string time;
		private string zone;

        ParkingDataLayer objDAL = new ParkingDataLayer();

        public void RegisterVehicle(double balance, string plateNo,string date, string time, string zone)
        {

            objDAL.InsertData(balance, plateNo, date, time, zone);
        }

        //public double getBalance(double balance)
       // {
            //string connStr2 = "Data Source=DESKTOP-1U2ADK2\\SQLEXPRESS;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
            //SqlConnection conn2 = new SqlConnection(connStr2);
            //conn2.Open();
            //SqlCommand cmd2 = new SqlCommand("SELECT [amount] FROM [dbo].[Reload]");
            //cmd2.CommandType = System.Data.CommandType.Text;
            //cmd2.Connection = conn2;

            //string temp2 = "";
            //SqlDataReader reader2 = cmd2.ExecuteReader();
            //reader2.Read();
            //temp2 += reader2["amount"];
            //conn2.Close();
            //return Convert.ToDouble(temp2);
        //}

        //public string getTime(string time)
        //{
            //string connStr2 = "Data Source=DESKTOP-1U2ADK2\\SQLEXPRESS;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False;ApplicationIntent=ReadWrite;MultiSubnetFailover=False";
            //SqlConnection conn2 = new SqlConnection(connStr2);
            //conn2.Open();
            //SqlCommand cmd2 = new SqlCommand("SELECT [time] FROM [dbo].[Parking]");
            //cmd2.CommandType = System.Data.CommandType.Text;
            //cmd2.Connection = conn2;

            //string temp2 = "";
            //SqlDataReader reader2 = cmd2.ExecuteReader();
            //reader2.Read();
            //temp2 += reader2["time"];
            //conn2.Close();
            //return temp2;
        //}

     

        public Parking(){

		}

		~Parking(){

		}

		public void AddParking(){

		}

		public void DisplayMessage(){

		}

		public void payParking(){

            if (time == "1")
            {
                balance = balance - 0.4;
            }
            else if (time == "2")
            {
                balance = balance - 0.8;
            }
            else if (time == "3")
            {
                balance = balance - 1.2;
            }
        }

		public void selectVehicle(){

		}

	}//end Parking

}//end namespace Application