///////////////////////////////////////////////////////////
//  Vehicle.cs
//  Implementation of the Class Vehicle
//  Generated by Enterprise Architect
//  Created on:      21-Apr-2019 12:23:45 AM
//  Original author: Afiq
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using DAL;


namespace BLL{
	public class Vehicle {

		private string color;
		private string model;
		private string plateNo;

        VehicleDataLayer objDAL = new VehicleDataLayer();



        public void RegisterVehicle(string color, string model, string plateNo)
        {

            objDAL.InsertData(color , model , plateNo);
        }

        public Vehicle(){

		}

		~Vehicle(){

		}

		public void checkVehicle(){

		}

		public void DisplayMessage(){

		}

		public void registerVehicle(){

		}

	}//end Vehicle

}//end namespace Application